import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { renderLines } from './lines';
import type { Lines, Mode } from '../../types';

/**
 * Parity guard against the retired vue-diff@1.2.4.
 *
 * The fixture was generated by running the original's own algorithm (its
 * `renderLines`, driven by diff-match-patch) over each input pair, so this
 * asserts byte-identical row output — not merely "looks similar". It is the
 * check that justifies calling this library a drop-in replacement, and it holds
 * despite the diff engine having been swapped for jsdiff.
 *
 * Regenerate only when a deviation is deliberate, and say why in the commit.
 */
interface ReferenceCase {
    /** prev input */
    p: string;
    /** current input */
    c: string;
    split: Lines[];
    unified: Lines[];
}

// Resolved from the project root: Vite does not give specs a file: import.meta.url.
const FIXTURE = 'tests/fixtures/parity/lines.reference.json';
const cases: ReferenceCase[] = JSON.parse(readFileSync(FIXTURE, 'utf8'));

describe('parity with vue-diff@1.2.4', () => {
    it('has a non-empty fixture', () => {
        expect(cases.length).toBeGreaterThan(0);
    });

    for (const { p, c, ...expected } of cases) {
        const label = `${JSON.stringify(p)} -> ${JSON.stringify(c)}`;

        for (const mode of ['split', 'unified'] as Mode[]) {
            it(`${mode}: ${label}`, () => {
                // Round-trip through JSON so `undefined` properties compare the
                // same way they do in the fixture.
                const actual = JSON.parse(JSON.stringify(renderLines(mode, p, c)));
                expect(project(actual, expected[mode])).toEqual(expected[mode]);
            });
        }
    }

    /**
     * Unified rows carry `chkWords`/`counterpart`, which the original never
     * emitted — it word-diffed only in split mode, where a row has two cells to
     * compare. Those fields are additive, so comparing them against a fixture
     * captured from vue-diff@1.2.4 would fail on a deliberate enhancement.
     *
     * Narrowing each row to the keys the original produced keeps the guard
     * strict where it matters: every field the original emitted must still match
     * exactly, and a missing or altered one still fails. Only fields the
     * original never had are ignored.
     */
    function project(actual: unknown, reference: unknown): unknown {
        if (Array.isArray(reference)) {
            return Array.isArray(actual)
                ? actual.map((row, i) => project(row, reference[i]))
                : actual;
        }
        if (reference && typeof reference === 'object' && actual && typeof actual === 'object') {
            return Object.fromEntries(
                Object.keys(reference).map((key) => [
                    key,
                    project(
                        (actual as Record<string, unknown>)[key],
                        (reference as Record<string, unknown>)[key],
                    ),
                ]),
            );
        }
        return actual;
    }
});
